[project]
name = "db"
version = "1.0.0"
requires-python = ">=3.14"
dependencies = [
    "common",
    "typer>=0.12.5",
    "yoyo-migrations>=9.0.0",
    "psycopg[binary]>=3.3.1",
    "python-dotenv>=1.2.1",
    "faker>=38.2.0",
    "psycopg2>=2.9.11",
]

[tool.hatch.build.targets.wheel]
packages = ["src/db"]
